/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vOZa9yH1zY9
 */
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";

export function Comp2() {
  return (
    <div className="flex flex-col h-screen">
      <header className="flex items-center justify-between px-6 py-4 border-b">
        <h1 className="text-2xl font-bold">Weather App</h1>
        <nav className="flex gap-4">
          <Link className="text-gray-500 hover:text-gray-900" href="#">
            Sign In
          </Link>
          <Link className="text-gray-500 hover:text-gray-900" href="#">
            Sign Up
          </Link>
        </nav>
      </header>
      <main className="flex-1 p-6">
        <div className="flex flex-col items-center justify-center space-y-4">
          <h2 className="text-2xl font-bold">Enter your location</h2>
          <form className="flex space-x-2">
            <Input placeholder="Location" type="text" />
            <Button type="submit">Get Weather</Button>
          </form>
        </div>
        <div className="mt-8">
          <Card>
            <CardHeader>
              <CardTitle>Weather Information</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-500">Temperature: 20°C</p>
              <p className="text-gray-500">Wind Speed: 10km/h</p>
              <p className="text-gray-500">Humidity: 70%</p>
            </CardContent>
          </Card>
        </div>
      </main>
      <footer className="flex items-center justify-center py-4 border-t">
        <p className="text-gray-500">© 2024 Acme Inc. All rights reserved.</p>
      </footer>
    </div>
  );
}
